name: Bug report
description: File a bug report
labels:
  - bug
body:
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
    validations:
      required: true
  - type: textarea
    id: what-expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
  - type: input
    id: version
    attributes:
      label: App Version
      description: What version of our software are you running?
      placeholder: 1.0.0, 1.0.0-beta01, etc. or commit hash
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system(s) are you seeing the problem on?
      multiple: true
      options:
        - Windows (x64)
        - macOS (x64)
        - Linux (x64)
        - Linux (ARM64)
        - Other (please specify in _Additional context_)
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: |
        Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks. 
        You can also attach files from `%APPDATA%\Roaming\WallProjections\Logs` or `~/.config/WallProjections/Logs`.
      render: shell
  - type: textarea
    id: additional-info
    attributes:
      label: Additional context
      description: |
        Add any other context about the problem here.
        If applicable, add screenshots to help explain your problem.
